
version: '3.4'

services:
  csharp:
    image: csharp
    build:
      context: .
      dockerfile: csharp/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
